version: '3.8'
services:
 notes:
   build:
     context: .
   ports:
     - 8000:8000
   environment:
     - SERVER_PORT=8000
     - DATABASE_CONNECTIONSTRING=mongodb+srv://admin:5mAdmjGPqI7YS2xQ@nodetuts.0qdti.mongodb.net/GoodJobGameCluster?retryWrites=true&w=majority

 mongo:
   image: mongo:4.2.8

